# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import secureemail_pb2 as secureemail__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in secureemail_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecureEmailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateKeys = channel.unary_unary(
                '/secureemail.SecureEmailService/GenerateKeys',
                request_serializer=secureemail__pb2.EmptyRequest.SerializeToString,
                response_deserializer=secureemail__pb2.KeyGenerationResponse.FromString,
                _registered_method=True)
        self.ProcessEmail = channel.unary_unary(
                '/secureemail.SecureEmailService/ProcessEmail',
                request_serializer=secureemail__pb2.ProcessEmailRequest.SerializeToString,
                response_deserializer=secureemail__pb2.EncryptedEmail.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/secureemail.SecureEmailService/VerifyEmail',
                request_serializer=secureemail__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=secureemail__pb2.Email.FromString,
                _registered_method=True)


class SecureEmailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureEmailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKeys,
                    request_deserializer=secureemail__pb2.EmptyRequest.FromString,
                    response_serializer=secureemail__pb2.KeyGenerationResponse.SerializeToString,
            ),
            'ProcessEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessEmail,
                    request_deserializer=secureemail__pb2.ProcessEmailRequest.FromString,
                    response_serializer=secureemail__pb2.EncryptedEmail.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=secureemail__pb2.VerifyEmailRequest.FromString,
                    response_serializer=secureemail__pb2.Email.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secureemail.SecureEmailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secureemail.SecureEmailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecureEmailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secureemail.SecureEmailService/GenerateKeys',
            secureemail__pb2.EmptyRequest.SerializeToString,
            secureemail__pb2.KeyGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secureemail.SecureEmailService/ProcessEmail',
            secureemail__pb2.ProcessEmailRequest.SerializeToString,
            secureemail__pb2.EncryptedEmail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secureemail.SecureEmailService/VerifyEmail',
            secureemail__pb2.VerifyEmailRequest.SerializeToString,
            secureemail__pb2.Email.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
