# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secureemail.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'secureemail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11secureemail.proto\x12\x0bsecureemail\"I\n\x05\x45mail\x12\x12\n\nemail_body\x18\x01 \x01(\x0c\x12,\n\x0b\x61ttachments\x18\x02 \x03(\x0b\x32\x17.secureemail.Attachment\"/\n\nAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\xa6\x01\n\x0e\x45ncryptedEmail\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x19\n\x11\x65ncrypted_des_key\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x19\n\x11\x65ncrypted_content\x18\x04 \x01(\x0c\x12?\n\x15\x65ncrypted_attachments\x18\x05 \x03(\x0b\x32 .secureemail.EncryptedAttachment\"8\n\x13\x45ncryptedAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"n\n\x13ProcessEmailRequest\x12!\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x12.secureemail.Email\x12\x18\n\x10private_key_sign\x18\x02 \x01(\x0c\x12\x1a\n\x12public_key_encrypt\x18\x03 \x01(\x0c\"\x80\x01\n\x12VerifyEmailRequest\x12\x34\n\x0f\x65ncrypted_email\x18\x01 \x01(\x0b\x32\x1b.secureemail.EncryptedEmail\x12\x1b\n\x13private_key_encrypt\x18\x02 \x01(\x0c\x12\x17\n\x0fpublic_key_sign\x18\x03 \x01(\x0c\"\x83\x01\n\x15KeyGenerationResponse\x12\x18\n\x10private_key_sign\x18\x01 \x01(\x0c\x12\x17\n\x0fpublic_key_sign\x18\x02 \x01(\x0c\x12\x1b\n\x13private_key_encrypt\x18\x03 \x01(\x0c\x12\x1a\n\x12public_key_encrypt\x18\x04 \x01(\x0c\"\x0e\n\x0c\x45mptyRequest2\xf6\x01\n\x12SecureEmailService\x12M\n\x0cGenerateKeys\x12\x19.secureemail.EmptyRequest\x1a\".secureemail.KeyGenerationResponse\x12M\n\x0cProcessEmail\x12 .secureemail.ProcessEmailRequest\x1a\x1b.secureemail.EncryptedEmail\x12\x42\n\x0bVerifyEmail\x12\x1f.secureemail.VerifyEmailRequest\x1a\x12.secureemail.Emailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secureemail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAIL']._serialized_start=34
  _globals['_EMAIL']._serialized_end=107
  _globals['_ATTACHMENT']._serialized_start=109
  _globals['_ATTACHMENT']._serialized_end=156
  _globals['_ENCRYPTEDEMAIL']._serialized_start=159
  _globals['_ENCRYPTEDEMAIL']._serialized_end=325
  _globals['_ENCRYPTEDATTACHMENT']._serialized_start=327
  _globals['_ENCRYPTEDATTACHMENT']._serialized_end=383
  _globals['_PROCESSEMAILREQUEST']._serialized_start=385
  _globals['_PROCESSEMAILREQUEST']._serialized_end=495
  _globals['_VERIFYEMAILREQUEST']._serialized_start=498
  _globals['_VERIFYEMAILREQUEST']._serialized_end=626
  _globals['_KEYGENERATIONRESPONSE']._serialized_start=629
  _globals['_KEYGENERATIONRESPONSE']._serialized_end=760
  _globals['_EMPTYREQUEST']._serialized_start=762
  _globals['_EMPTYREQUEST']._serialized_end=776
  _globals['_SECUREEMAILSERVICE']._serialized_start=779
  _globals['_SECUREEMAILSERVICE']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
